SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';


-- -----------------------------------------------------
-- Table `CONTA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CONTA` ;

CREATE  TABLE IF NOT EXISTS `CONTA` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT ,
  `DESCRICAO` VARCHAR(200) NOT NULL ,
  PRIMARY KEY (`ID`) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CATEGORIA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CATEGORIA` ;

CREATE  TABLE IF NOT EXISTS `CATEGORIA` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT ,
  `DESCRICAO` VARCHAR(200) NOT NULL ,
  `PAI` INT UNSIGNED NULL ,
  PRIMARY KEY (`ID`) ,
  INDEX `IDX_CATEGORIA_CATEGORIA1` (`PAI` ASC) ,
  CONSTRAINT `IDX_CATEGORIA_CATEGORIA1`
    FOREIGN KEY (`PAI` )
    REFERENCES `CATEGORIA` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LANCAMENTO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LANCAMENTO` ;

CREATE  TABLE IF NOT EXISTS `LANCAMENTO` (
  `ID` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT ,
  `DESCRICAO` VARCHAR(255) NOT NULL ,
  `DATA` DATE NOT NULL ,
  `VALOR` DECIMAL(10,2) NOT NULL ,
  `CONTA_ID` INT UNSIGNED NOT NULL ,
  `CATEGORIA_ID` INT UNSIGNED NOT NULL ,
  PRIMARY KEY (`ID`) ,
  INDEX `IDX_LANCAMENTO_CONTA` (`CONTA_ID` ASC) ,
  INDEX `IDX_LANCAMENTO_CATEGORIA1` (`CATEGORIA_ID` ASC) ,
  CONSTRAINT `IDX_LANCAMENTO_CONTA`
    FOREIGN KEY (`CONTA_ID` )
    REFERENCES `CONTA` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `IDX_LANCAMENTO_CATEGORIA1`
    FOREIGN KEY (`CATEGORIA_ID` )
    REFERENCES `CATEGORIA` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `USUARIO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `USUARIO` ;

CREATE  TABLE IF NOT EXISTS `USUARIO` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT ,
  `NOME` VARCHAR(100) NOT NULL ,
  `LOGIN` VARCHAR(60) NOT NULL ,
  `SENHA` VARCHAR(40) NOT NULL ,
  `DATA_HORA` DATETIME NOT NULL ,
  `PERFIL` VARCHAR(100) NOT NULL ,
  PRIMARY KEY (`ID`) )
ENGINE = InnoDB;



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
